// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXenbyM40ymNsvGf2Ue9kXDwyNH3tSnI',
    appId: '1:659643572325:web:fdb3990bb09032a2baa68c',
    messagingSenderId: '659643572325',
    projectId: 'multivendorapp-9a087',
    authDomain: 'multivendorapp-9a087.firebaseapp.com',
    storageBucket: 'multivendorapp-9a087.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQzLTUlrGW3LpjrN8JJFb0Yia6VxiAsk',
    appId: '1:659643572325:android:9e299e845548d9c4baa68c',
    messagingSenderId: '659643572325',
    projectId: 'multivendorapp-9a087',
    storageBucket: 'multivendorapp-9a087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJxM-OKXrJrRcBiDsMTZvVo1Yqx2PocA',
    appId: '1:659643572325:ios:617e4cc610f0ee10baa68c',
    messagingSenderId: '659643572325',
    projectId: 'multivendorapp-9a087',
    storageBucket: 'multivendorapp-9a087.appspot.com',
    iosClientId: '659643572325-b0lg0oifs14d05e8gbrrfdbttbjqcm4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendorOnlyApp',
  );
}
